name: audio_classification
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.12.12
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.4.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-lru==2.1.0
      - attrs==25.4.0
      - audioread==3.1.0
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fqdn==1.5.1
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.78.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keras==3.13.2
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markdown==3.10.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - msgpack==1.1.2
      - namex==0.1.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numba==0.63.1
      - numpy==2.3.5
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==3.0.1
      - pandocfilters==1.5.1
      - parso==0.8.6
      - pillow==12.1.1
      - platformdirs==4.9.2
      - pooch==1.9.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.5
      - psutil==7.2.2
      - pure-eval==0.2.3
      - pycparser==3.0
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pywinpty==3.0.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.3.2
      - rpds-py==0.30.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - send2trash==2.1.0
      - six==1.17.0
      - soundfile==0.13.1
      - soupsieve==2.8.3
      - soxr==1.0.0
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - wrapt==2.1.1
prefix: C:\Users\rabde\anaconda3\envs\audio_classification
